### ISSUE TITLE
Can't be installed directly into fresh Symfony 7.x project

### ISSUE THREAD

**Issue by bytes-max** [m4n50n/telegram_bot_bundle#6]
When attempting to require this package, it throws an error:

```
Symfony operations: 2 recipes (cdf79fbb1797ca8ed0bb4f0042340a8f)
  - Configuring symfony/monolog-bundle (>=3.7): From github.com/symfony/recipes:main
  - Configuring m4n50n/telegram-bot-bundle (>=0.1): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 213:
!!                                                                             
!!    The child config "bots" under "telegram_bot_bundle" must be configured.  
!!                                                                             
!!  
!!  
Script @auto-scripts was called via post-update-cmd
```

composer.json:
```
  "require": {
        "php": ">=8.2",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "m4n50n/telegram-bot-bundle": "*",
        "symfony/apache-pack": "^1.0",
        "symfony/config": "7.1.*",
        "symfony/console": "7.1.*",
        "symfony/dotenv": "7.1.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "7.1.*",
        "symfony/runtime": "7.1.*",
        "symfony/security-bundle": "7.1.*",
        "symfony/translation": "7.1.*",
        "symfony/uid": "7.1.*",
        "symfony/web-link": "7.1.*",
        "symfony/yaml": "7.1.*",
        "twig/extra-bundle": "^3.10"
    },
```

**Comment by m4n50n** [comment]
Hi @nopenopenope, sorry for the delay. This error is because the installation did not use the recipe and therefore the telegram_bot_bundle.yaml file was not automatically created. All you need is to add a *telegram_bot_bundle.yaml* file inside config/packages with content like this that follows this structure:

```
telegram_bot:
  bots:
    example_bot:
      # Required #
      key: ""
      username: ""

      webhook:
        url: ""
        max_connections: ""

      commands:
        paths:
          - ""

      # Optional #
      # admins:
      #   - 123456789 # Admin user id in Telegram

      # mysql:
      #   enabled: true # false by default
      #   host: mysql
      #   user: "root"
      #   password: "%env(BOT_MYSQL_ROOT_PASSWORD)%"
      #   database: "%env(BOT_MYSQL_DB)%"

      # log:
      #   enabled: true # false by default
      #   debug: "%env(LOG_DEBUG_FILE_PATH)%"
      #   error: "%env(LOG_ERROR_FILE_PATH)%"
      #   update: "%env(LOG_UPDATE_FILE_PATH)%"

      # paths:
      #   download: "%env(DOWNLOADS_PATH)%"
      #   upload: "%env(UPLOADS_PATH)%"

      # limiter:
      #   enabled: true # false by default
```

However, in the README of the repository you have all the documentation.

Please let me know of any problems, thank you!😀
